# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 15
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - ToDo
# Label to use when marking an issue as stale
staleLabel: Pending closure
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  This issue has been automatically closed because it has not had any comments for a while, feel free to reopen it if needed
